### PR TITLE
Removed commas from varlabel for output

### PR DESCRIPTION
**Pull request by rchayes13**
When there are commas in the varlabel, the output is off. I just removed all commas from the variable labels because I couldn't quickly think of a better way to keep them in.

### CODE REVIEW

**Comment by umeditor** [comment]
According to [this](http://stackoverflow.com/a/769675), "Fields containing line breaks (CRLF), double quotes, and commas should be enclosed in double-quotes" and "if double-quotes are used to enclose fields, then a double-quote appearing inside a field must be escaped by preceding it with another double quote."

So, I'd update the code to replace '"' with '""' and then output all values with quotes. Or, better yet, use write.csv to create the output file as it can handle to escaping on its own.

**Comment by rchayes13** [comment]
I'm not really sure where you mean. I tried using the double quotes in the cat statement (i.e. ""varlab""; I also tried using backslahes) but got errors like: 

Error: unexpected symbol in:
"          var,
          ""varlab"
Execution halted

I didn't want to spend a lot of time reworking it for write.csv so I thought just removing all commas from variable labels would be ok? It works as expected.

**Comment by umeditor** [comment]
Commas are only one type of character that will cause problems - quotes and line breaks are also problems. We could fix all these ourselves, but write.csv already does it correctly. I'll see if I can get to it today and update your patch.

**Comment by umeditor** [comment]
I've updated the patch to use write.csv and write.table.

**Comment by rchayes13** [comment]
Thanks!

**Pull request merged**
