### PR TITLE
Scan labels for possible PII

### PR DESCRIPTION
**Pull request by umeditor**

### CODE REVIEW

**Comment by umeditor** [comment]
Possible fix for #21.

**Comment by umeditor** [comment]
@rchayes13 let me know if this works as you'd expect.

**Comment by rchayes13** [comment]
Yes, this works perfectly. I tested it on data where the varnames are of the form a## but the variable labels are informative (e.g. year of birth, month of birth). It found a lot of potential PII based on the variable labels containing PII strings--but it might work too well.

For instance, some of the variable labels take the form: "Does the household have [x,y,x]?" or "Did mother wash child's hand before [a,b,c]?" Because "house" and "child" are both PII strings, a bunch of indicator variables were flagged as PII. So, I'm wondering if we can (or should) be more strict when we are scanning variable labels for PII?

But mechanically, it does exactly what I would expect. Thanks!

**Comment by umeditor** [comment]
What did you have in mind with being "more strict" when scanning labels?

**Comment by umeditor** [comment]
I also just added a --scan-lables option, which is off by default. That way, if people want to scan labels, the can, but it doesn't happen by default. Otherwise, there might be too much noise.

**Comment by rchayes13** [comment]
@umeditor I don't have a good idea of what "more strict" would mean. My thought was just that in some large datasets the noise from the varlabel scan might overwhelm its benefit. I think your edit is good; if no PII is found on an initial run without the label scan, then one add the label scan option to see if it catches anything new.

**Comment by umeditor** [comment]
Okay - I'll merge this PR then, which makes label scanning optional and off by default.

**Pull request merged**
